runtime: nodejs10
instance_class: F1
automatic_scaling:
  max_instances: 1
handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /vendor
  static_dir: vendor
- url: /img
  static_dir: img

skip_files:
- ^node_modules/.*$