runtime: nodejs
env: flex
env_variables:
  SQL_USER: iankang
  SQL_PASSWORD: livingwater
  SQL_DATABASE: csuva
  INSTANCE_CONNECTION_NAME: csuva-252520:us-east1:csuva
beta_settings:
  cloud_sql_instances: csuva-252520:us-east1:csuva
  
handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /vendor
  static_dir: vendor
- url: /img
  static_dir: img